name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      project_type:
        description: 'Type of the project (portal or microapp)'
        required: true
        default: 'portal'
        type: string
      project_name:
        description: 'Name of the microapp (required if project_type is microapp)'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_type: [${{ github.event.inputs.project_type }}]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Execute Build
        run: |
          if [ "${{ matrix.project_type }}" == "portal" ]; then
            gh workflow run build-portal.yml
          else
            gh workflow run build-microapp.yml -f project_name=${{ github.event.inputs.project_name }}
          fi
